export const products = [
  {
    name: "Chleb pszenny",
    description: "Świeży chleb pszenny, idealny na kanapki.",
    image: "/images/bread.png",
    price: 2.5,
    category: "bread",
    shop: "biedronka",
  },
  {
    name: "Jabłka",
    description: "Słodkie i soczyste jabłka, idealne na przekąskę.",
    image: "/images/apple.png",
    price: 3.0,
    category: "fruits",
    shop: "lidl",
  },
  {
    name: "Marchewki",
    description: "Chrupiące marchewki, pełne witamin.",
    image: "/images/carrot.png",
    price: 1.8,
    category: "vegetables",
    shop: "kaufland",
  },
  {
    name: "Kurczak",
    description: "Świeży kurczak, doskonały do różnych potraw.",
    image: "/images/chicken.png",
    price: 9.5,
    category: "meat",
    shop: "biedronka",
  },
  {
    name: "Mleko",
    description: "Pełne mleko, źródło wapnia.",
    image: "/images/milk.jpg",
    price: 2.2,
    category: "dairy",
    shop: "lidl",
  },
  {
    name: "Czekolada",
    description: "Pyszna czekolada mleczna.",
    image: "/images/chocolate.png",
    price: 4.5,
    category: "sweets",
    shop: "kaufland",
  },
  {
    name: "Cola",
    description: "Lekko gazowana cola, orzeźwiający napój.",
    image: "/images/cola.jpg",
    price: 2.0,
    category: "drinks",
    shop: "biedronka",
  },
  {
    name: "Pomarańcze",
    description: "Słodkie i soczyste pomarańcze.",
    image: "/images/orange.png",
    price: 3.5,
    category: "fruits",
    shop: "lidl",
  },
  {
    name: "Ziemniaki",
    description: "Świeże ziemniaki, idealne na ziemniaczane placki.",
    image: "/images/potato.png",
    price: 2.0,
    category: "vegetables",
    shop: "kaufland",
  },
  {
    name: "Wołowina",
    description: "Kawałki wołowiny do duszenia.",
    image: "/images/beef.png",
    price: 12.0,
    category: "meat",
    shop: "biedronka",
  },
  {
    name: "Jogurt naturalny",
    description: "Prosty i zdrowy jogurt naturalny bez dodatków.",
    image: "/images/yogurt.png",
    price: 2.5,
    category: "dairy",
    shop: "lidl",
  },
  {
    name: "Ciastka owsiane",
    description: "Delikatne ciastka owsiane, idealne na śniadanie.",
    image: "/images/biscuit.png",
    price: 4.0,
    category: "sweets",
    shop: "kaufland",
  },
  {
    name: "Herbata czarna",
    description: "Tradycyjna herbata czarna o intensywnym smaku.",
    image: "/images/black-tea.png",
    price: 3.0,
    category: "drinks",
    shop: "biedronka",
  },
  {
    name: "Baton energetyczny",
    description: "Baton energetyczny, idealny na przekąskę w ciągu dnia.",
    image: "/images/energy-bar.png",
    price: 5.5,
    category: "sweets",
    shop: "lidl",
  },
  {
    name: "Sok jabłkowy",
    description: "Świeży sok jabłkowy, pełen witamin.",
    image: "/images/apple-juice.jpg",
    price: 2.8,
    category: "drinks",
    shop: "kaufland",
  },
  {
    name: "Ogórki",
    description: "Kiszzone ogórki, idealne do kanapek.",
    image: "/images/cucumber.png",
    price: 3.5,
    category: "vegetables",
    shop: "biedronka",
  },
  {
    name: "Szynka",
    description: "Klasyczna szynka, doskonała do kanapek.",
    image: "/images/ham.png",
    price: 8.0,
    category: "meat",
    shop: "lidl",
  },
  {
    name: "Ser gouda",
    description: "Ser gouda, świetny na przekąski.",
    image: "/images/cheese.png",
    price: 6.5,
    category: "dairy",
    shop: "kaufland",
  },
  {
    name: "Koktajl truskawkowy",
    description: "Owocowy koktajl truskawkowy na bazie jogurtu.",
    image: "/images/smoothie.png",
    price: 4.5,
    category: "drinks",
    shop: "biedronka",
  },
  {
    name: "Makaron pełnoziarnisty",
    description: "Pełnoziarnisty makaron do zdrowych dań.",
    image: "/images/pasta.png",
    price: 3.2,
    category: "dairy",
    shop: "lidl",
  },
  {
    name: "Gruszki",
    description: "Soczyste gruszki, doskonałe na deser.",
    image: "/images/pear.png",
    price: 3.8,
    category: "fruits",
    shop: "kaufland",
  },
  {
    name: "Sałatka grecka",
    description: "Tradycyjna sałatka grecka z dodatkiem sera feta.",
    image: "/images/greek-salad.jpg",
    price: 7.0,
    category: "vegetables",
    shop: "biedronka",
  },
  {
    name: "Kabanosy",
    description: "Kabanosy, idealne na przekąskę.",
    image: "/images/kabanos.jpg",
    price: 5.5,
    category: "meat",
    shop: "lidl",
  },
  {
    name: "Masło orzechowe",
    description: "Masło orzechowe bez dodatku cukru.",
    image: "/images/peanut-butter.png",
    price: 6.0,
    category: "sweets",
    shop: "kaufland",
  },
  {
    name: "Woda gazowana",
    description: "Czysta woda gazowana, orzeźwiający napój.",
    image: "/images/sparkling-water.png",
    price: 1.5,
    category: "drinks",
    shop: "biedronka",
  },
  {
    name: "Ciasto marchewkowe",
    description: "Pyszne ciasto marchewkowe z kremem śmietanowym.",
    image: "/images/carrot-cake.png",
    price: 8.5,
    category: "sweets",
    shop: "lidl",
  },
  {
    name: "Ryż basmati",
    description: "Ryż basmati, idealny dodatek do dań kuchni orientalnej.",
    image: "/images/rice.png",
    price: 4.0,
    category: "vegetables",
    shop: "kaufland",
  },
];
