import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";
import AuthContext from "@/app/context/AuthContext";
import { Toaster } from "react-hot-toast";
import StoreProvider from "@/app/providers/StoreProvider";
import AccountMenu from "./components/AccountMenu";
import Wrapper from "../components/Wrapper";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface AccountLayoutProps {
  children: React.ReactNode;
}

const AccountLayout: React.FC<AccountLayoutProps> = ({ children }) => {
  return (
    <Wrapper>
      <div className="flex py-12">
        <AccountMenu />
        {children}
      </div>
    </Wrapper>
  );
};

export default AccountLayout;
